apiVersion: v1
kind: Service
metadata:
  name: adhithia-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: adhithia-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
